[package]
name = "chigraph"
version = "0.1.0"
authors = ["Russell Greene <russellgreene8@gmail.com>"]

[dependencies]
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
uuid = "^0.6"

[lib]
name = "chigraph"
path = "src/lib.rs"

[[bin]]
name = "chi-rs"
path = "src/bin.rs"
